### ISSUE TITLE
After accessing via browser `https://localhost/443`, I've got a `404 page not found`

### ISSUE THREAD

**Issue by Luk-kar** [jamesgreenblue/metabase-traefik-compose#1]
1. I have followed the README
2. I changed the port `80` to `8000`, the port `80` was already occupied in my Ubuntu system
3. The docker built successfully images in the docker-compose.yml
4. After logging to the port `https://localhost/443`, I've got a response `404 page not found`

Is it an expected behavior?

**Comment by jamesgreenblue** [comment]
Hello,

This compose is intended for use in small to medium sized production environments - please test by deploying onto a clean dedicated or virtual machine (VM) with DNS setup and ports 80/443 open so that the SSL certificates can be generated for your chosen URL. 

If you want to test Metabase on your local machine, there are instructions for this at: https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker

If you aren't confident in your ability to self host then you can support the project by using their cloud offering, see: https://www.metabase.com/cloud/

With goodwill,
James
