### ISSUE TITLE
Metabase using SSL its not working

### ISSUE THREAD

**Issue by dpaes** [jamesgreenblue/metabase-traefik-compose#2]
I tried to use the docker compose file, but using my traefik with cloudflared already installed in my local test server. But only go to 404. i think he its not receiving https requests. i already use another applications in my machine to local tests using tunnels of cloudflare but this is the first time i cant send an request directly to an application.

i'm using wsl ubuntu 20.04 with docker desktop in my windows 10. Docker swarm with deployment for 4GB an 2 cpus for metabase and 1 cpu and 4GB for postgres container. But he finish the migrations but its not allow to acess with DNS appointment

**Comment by dpaes** [comment]
i have changed the cloudflare rules to http and worked

**Comment by jamesgreenblue** [comment]
Hi @dpaes

Port 80 (`http`) needs to be open so that the Let's Encrypt cert bot can verify the domain and generate SSL certificates. The Traefik configuration redirects any subsequent `http` requests to `https`. 

From https://letsencrypt.org/docs/allow-port-80/:
> Our recommendation is that all servers meant for general web use should offer both HTTP on port 80 and HTTPS on port 443. They should also send redirects for all port 80 requests

Glad to hear you figured out a solution - hope the rest of your setup goes smoothly.

With goodwill,
James
